### ISSUE TITLE
Add "role specification" as requirement for bonded roles in phase-zero.adoc

### ISSUE THREAD

**Issue by csacher** [bisq-network/roles#54] opened 2017-12-12 07:01 UTC
phase-zero.adoc: https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc

In order to ensure the role specification completion of all assigned roles I will add it as a requirement in the phase zero document.

**Comment by cbeams** [comment] 2017-12-12 07:04
@csacher, I believe this is a duplicate of bisq-network/docs#19, yeah? I'll close on your confirmation.

**Comment by cbeams** [comment] 2017-12-12 07:05
Your title was better than mine, though :)

**Comment by cbeams** [comment] 2018-01-02 10:36
Closing as duplicated by bisq-network/docs#19 per https://github.com/bisq-network/roles/issues/54#issuecomment-350963324.

**Closed as completed by cbeams** 2018-01-02 10:36 UTC
