### ISSUE TITLE
Analytics Administrator

### ISSUE THREAD

**Issue by m52go** [bisq-network/roles#91] opened 2019-09-27 13:41 UTC
Main duties:

Optimize Matomo setup for insights on traffic, conversions, etc. Report traffic for main sites here, monthly.

Team: TBD
Primary owner: @FKrauss 
Secondary owner: @m52go

**Comment by FKrauss** [comment] 2019-09-28 12:02
Analytics Report - Sept 2019
===
Brief
----
We're still accumulating traffic data in order to make comparisons month over month so this report will seem a bit raw. We have configured the downloads tracking on the 9th of Sept and we started gathering visits on the first week of august.

![vists x downloads](https://user-images.githubusercontent.com/4820683/65815871-07773200-e1f5-11e9-8e4b-129752ced879.png)



How is our website traffic going?
----
* We are getting 700-900 visits per day (not counting ad blocker users)
* people spend on average 2 min on the site (when they don't bounce), that's a good amount of time to download the software and move away. This is a hard number to compare to other exchanges as other services have the exchange itself in the website, which leads to much higher time spent (i.e. coinbase [~6 min](https://www.similarweb.com/website/coinbase.com#overview) and bitstamp [~6 min as well](https://www.similarweb.com/website/bitstamp.net#overview) 
* abount 15% of them end up downloading a version of our application, which is also seems to be a pretty high rate compared to conversion rates in other verticals (This is the first time I see a conversion rate on a "service" like Bisq, let's see how it evolves over time)
* as we've been through 2 update cycles since we started measuring, the downloads from the website do not seem to correlate with updates. << which is a great thing as we can use these numbers to infer new installs.

Graph:
![2019-09-28 13_43_57-Bisq - From 2019-08-30 to 2019-09-28 - Web Analytics Reports - Matomo - Dissente](https://user-images.githubusercontent.com/4820683/65815953-2a561600-e1f6-11e9-84e1-0ea86c911596.png)
conversion rate: a user who downloads any version of our app

Top 5 markets in traffic terms
---
Strangely enough a lot of our traffic is in countries where we don't have a ton of volume:
- US
- UK
- BR (Some orders open, not sure if my outreach is yielding [see here](https://bisq.network/markets/?currency=btc_brl))
- RU (very few offers in RUB, maybe Alts are generating this organic traffic  [see here](https://bisq.network/markets/?currency=btc_rub)) - although in absolute terms, Russia still pales in comparison with the US
- ES
![2019-09-28 13_47_34-Bisq - From 2019-09-01 to 2019-09-28 - Web Analytics Reports - Matomo - Dissente](https://user-images.githubusercontent.com/4820683/65815988-ab151200-e1f6-11e9-9911-96755b7713bc.png)

Downloads correlate directly with traffic. Nothing to add.

Traffic sources
---
* 40% of our traffic is direct > that is a good indication of a strong brand
* 27% search engines (Google being the top)
* 27% other sites (which shows the specialised media likes us)
* 5% social media (includes youtube videos)

Interesting to note that not always youtube videos lead to direct links. A lot of content on youtube creates direct access & search queries for brands. Which is one of the explanations behind why we know we have plenty of youtube content about bisq but yet it represents so little in terms of traffic. In this sense, youtube works a bit like TV, creates awareness, but the user journey will happen at a later point (via a Search or a direct access)

Devices
---
About 2 thirds of our traffic is desktop
the other third is mainly on phones (27%) and they do have some downloads. apparently people misunderstand the word "app" and try to download as they land on the page. This cohort is yet too small to justify any specialized action to address this problem.

Other Notable highlights
----
* Wiz posted a large thread on [twitter](https://twitter.com/wiz/status/1175971952403443713) drawing attention to bisq. The tweetstorm generated more than 100k Impressions on twitter and a ton of engagement. We did not see a direct increase in traffic as https://bisq.network was mentioned many tweets deep. There is no way for us to assess it yet but from my experience this type of engagement usually culminates in higher search traffic as people read the full thing and later start searching for it (as opposed to scrolling up to grab the link). Moving forward we can add specific tracking to links on twitter to understand how our social media content strategy is yielding downloads.


Misc & info
---
* Wiz and I decided to leave the Matomo script named Matomo as to give users a transparent way to opt out (as opposed to obscuring the tracking script with some "bisqalytics.js" mumbo jumbo to dodge ad blockers). Because of the nature of our audience we probably have a VERY high ad blocker usage rate. So, for now we have no way to estimate the magnitude by which the data from matomo is understated.
* to preserve user privacy we set the privacy settings to maximum. One of the results of that is we can't see users' cities, only countries and sometimes only regions
* the concepts and definitions used here are Matomo concepts, which are mirrored from Google analytics (hits, sessions, users). They can differ and that could change the insights. We'll keep you posted as our knowledge of it evolves
* download tracking was configured on the 8th of september, which means 2 update cycles
* So far it doesn't look like updates from the bisq application count against these numbers. Downloads seem to be only website originated downloads (which definition-wise would include New Downloads and whoever failed to download via the update link in the app) >>> looking at downloads from the website is a valid way of assessing new user growth 


Q&A
----
If you have any particular questions regarding our traffic that you'd like answered, post here as comments and we'll make sure we're instrumented to answer them

**Comment by FKrauss** [comment] 2019-11-07 21:36
Brief
----
This month as we had, at the end, a new version coming out it is natural that our traffic would also go up. But it didn't coincide with the launch dates very much. Taking a longer view it does look like traffic is picking up in general rather than caused by a single issue or a major release.

![image 1](https://user-images.githubusercontent.com/4820683/68429071-b40de180-01ad-11ea-848f-bf4ee45d98e1.png)

Above, taking a longer view an grouping the data per week we see a clear uptrend in both traffic and Downloads. Trying to parse if that's country specific or not makes us see that the uptrend is present in both US and Europe which account for 56% and 30% of overall traffic, respectively: no single country apart from the US could be leading this trend.

The trend can be helped or even caused by the media talking about our major launches.

Channel wise, traffic has a similar distribution to what was previously reported.

Admin
----

- We need to update Matomo as we might be missing tracking in some sessions as seen by some errors in the UI
- We included all the recent launches to annotations in the tool so anyone using it can easily correlate spikes in Downloads to version releases
- We'll report more once there is more to report. For now we're still having not a lot to compare against, nor to detect trends.

**Comment by FKrauss** [comment] 2020-02-07 15:05
Analytics Report - Q4 recap & Jan
====

Looking at the website, not a lot happens. The traffic is very stable and the conversion rates hover around the same 15% value. Interesting to note that US/non-US there is a diff in conversion rates: US is consistently higher than non-US

![image](https://user-images.githubusercontent.com/4820683/74039293-df2cea80-49c1-11ea-92d7-43ec82b2cabf.png)




Activities
----
* labeling and adding importnat events, such as releases, podcast appearances, downtime, etc
* regular analysis to look for trends

Points to note
----
* **[Bounce rate](https://piwik.pro/glossary/bounce-rate/)** - Bounce in our website is pretty high, 50% of people who land on the front page, end their visit right there without any action (downloads included). 
![image](https://user-images.githubusercontent.com/4820683/74040209-8b230580-49c3-11ea-9749-f2d613085a40.png)

 With that in mind I wrote a proposal on how we can try to improve that. [See here](https://github.com/bisq-network/growth/issues/182)
* **US/non-US** -> I decided to break these down as the volume is 50/50 like this and, having the US in any other analysis will lead to always looking at the US as a whole, because it dwarfs any other variance. With that in mind, looking at the non-US cohort we have Germany and the UK leading the charts in visits which leads me to think that we could offer some more convenient payment methods for these tow European countries. **N26** could be a good candidate as its main market is Germany and seems to be as big as Revolut in overall users [see here](https://n26.com/en-eu/blog/5-million-announcement).
* we had a minor incident where the Matomo server was down on the 2nd of Feb (you can notice in the graph)
![image](https://user-images.githubusercontent.com/4820683/74039801-c5d86e00-49c2-11ea-9a70-9539444889eb.png)

**Comment by ripcurlx** [comment] 2020-02-17 08:40
> * **N26** could be a good candidate as its main market is Germany and seems to be as big as Revolut in overall users [see here](https://n26.com/en-eu/blog/5-million-announcement).

N26 is already supported in Bisq (Moneybeam) 😉

**Comment by FKrauss** [comment] 2020-02-17 09:24
> 
> 
> > * **N26** could be a good candidate as its main market is Germany and seems to be as big as Revolut in overall users [see here](https://n26.com/en-eu/blog/5-million-announcement).
> 
> N26 is already supported in Bisq (Moneybeam) 😉

That's cool! I didn't know it! Maybe we should rebrand it then, because I do see an uptick in friends & family getting N26 accounts, but never heard of Moneybeam

**Comment by FKrauss** [comment] 2020-02-17 09:32
Btw, based on [this](https://mag.n26.com/show-me-the-moneybeam-b0d70b766516) the trade message for moneybeam should be something with pizza in the beginning

**Comment by ripcurlx** [comment] 2020-02-17 09:58
> That's cool! I didn't know it! Maybe we should rebrand it then, because I do see an uptick in friends & family getting N26 accounts, but never heard of Moneybeam

<img width="593" alt="Bildschirmfoto 2020-02-17 um 10 57 58" src="https://user-images.githubusercontent.com/170962/74643061-67ef1780-5174-11ea-9f38-2c3398ea625c.png">

N26 is part of the label already

**Comment by FKrauss** [comment] 2020-03-08 12:33
Nothing in particular to report regarding February.

* traffic is stable
* downloads / conversion rates are stable

Some Admin tasks
* Removed 2 users from the matomo instance 
* added @MwithM, so he can carry out his new role as translation coordinator

**Comment by m52go** [comment] 2020-03-13 16:09
@FKrauss would you mind titling your updates with `## Cycle 11 report` so that we can more easily distinguish between comments and cycle reports?

**Comment by FKrauss** [comment] 2020-03-13 16:27
Sure! I was thinking about the same thing a while back. Will do on the next

**Comment by wiz** [comment] 2021-01-04 11:26
@FKrauss it seems this role is not active, any objection to un-assigning you and closing the role?

**Comment by cbeams** [comment] 2021-01-05 08:18
> @FKrauss it seems this role is not active, any objection to un-assigning you and closing the role?

It looks like this role was basically superseded by #88, which you're owning @wiz, is that correct? Makes sense to me as roles admin to close this accordingly. I'll just do it now for the sake of expediency. @FKrauss, please speak up if there's some misunderstanding.

**Comment by cbeams** [comment] 2021-01-05 08:19
Closing as superseded by #88 per comments above.

**Closed as completed by cbeams** 2021-01-05 08:19 UTC
Labels: was:superseded, team:growth

**Comment by cbeams** [comment] 2021-01-05 08:22
I also deleted the @bisq-network/matomo-admins team.

**Comment by FKrauss** [comment] 2021-01-05 18:10
> @FKrauss it seems this role is not active, any objection to un-assigning you and closing the role?

No objection at all. I have not contributed to it in a while. Matomo is there and collecting data but we haven't really used it for anything. I believe when @m52go  is ready to do some A/B testing on the website I can help him procure the data and make the analysis
